### ISSUE TITLE
Issue with patching shorthand if

### ISSUE THREAD

**Issue by gamax92** [picolove/picolove#12]
The current patcher for shorthand if's will put "end" after a comment if there is one:
`if (expression) expression --comment`
becomes
`if expression then expression --comment end`

It should detect if the line contains a comment and place the end before the comment.

EDIT:
I've also noticed the line regarding `or` reads `b:find('%f[%w]or%f[W]')`, should it read `b:find('%f[%w]or%f[%W]')` like the others?

**Comment by ftsf** [comment]
Thanks!

Aware of many issues with the shorthand parser, unfortunately they're not trivial to fix without writing a modified lua parser =( I tried to do a poor implementation that covered most cases I found in existing projects, but it definitely needs work.

That bug you found is handy though, it should indeed be `%W`.

**Comment by gamax92** [comment]
Well, this one is pretty trivial to fix, just look for a comment and split b into two parts, the code before the comment, and the comment with any spaces behind it

Even if there are examples where that's incorrect (strings maybe?, this can also be detected though) it fixes quite a few carts

**Comment by ftsf** [comment]
resolved by 1b2a0aa66cbe330c6c0d12376aecc4d274a1700a
