### ISSUE TITLE
No longer seeing text output from print?

### ISSUE THREAD

**Issue by gingerbeardman** [picolove/picolove#4]
``` lua
function _init()
end

function _update()
end

function _draw()
  cls()
  --color(6)
  print("can you see this?")
end
```

It seems that color is being set to black somehow? 

you can see this if you uncomment the color(7) command. this does not work if color is _init or _update

**Comment by gingerbeardman** [comment]
fixed in https://github.com/ftsf/picolove/pull/5

**Comment by ftsf** [comment]
thanks!
