### ISSUE TITLE
A parameter to set "stricted mode Pico-8"

### ISSUE THREAD

**Issue by mdtrooper** [picolove/picolove#51]
Hi.

I think that is good to set a parameter to set "stricted mode Pico-8"

Thanks.

**Comment by Shoozza** [comment]
How would that mode differ from the current implementation?

**Comment by mdtrooper** [comment]
This is a good question. Well, the picolove with the strict param set runs with the limitations (memory and others...) of pico-8.

**Comment by vanfanel** [comment]
@mdtrooper : from what I understand, it seems these limitations are arbitrary, so what would "strict pico-8 mode" bring? Maybe rejecting to run non-strict pico-8 games if their resource requeriments are above those of the original, closed pico-8 implementation?
Maybe not using them (if you don't want) would be enough in that case...

**Comment by Shoozza** [comment]
If we want to add this, we'd need to collect all limitations first.
Note that limitations change between pico-8 versions.

If someone can list all the limitations that would be a start.

**Comment by gamax92** [comment]
Implementing a memory limiter isn't really possible when your implementation of a Lua based product is in Lua itself.
CPU limits is somewhat possible but the whole picolove is writtein in Lua also makes this not fully accurate
picolove would need to be rewritten to not use any string metatable to restrict pico-8 code from accessing the string metatable too

(Also hi, sorry I've been away for a long time)

**Comment by Shoozza** [comment]
Ah I see - Thanks for the clarifications.  
I don't think I'd want to rewrite picolove to support these limitations.  
(Welcome back!)

**Comment by Shoozza** [comment]
Wontfix see comment above
