### ISSUE TITLE
PNG detection

### ISSUE THREAD

**Issue by SaphireLattice** [picolove/picolove#52]
Maybe png detection should be done not by the extension of the file but by the png magic string?

**Comment by Shoozza** [comment]
What would be the use case for this?

**Comment by gamax92** [comment]
So that even if you have a file name "some_p8_cart", if the first eight bytes start with "\137PNG\r\n\26\n" then treat it as a png and use the image loader, You can similarly check for the p8 text header and load with the appropriate loader.
