### ISSUE TITLE
Use of pal() not reseting transparency

### ISSUE THREAD

**Issue by TheNuSan** [picolove/picolove#53]
Hi, a call to pal() should also reset palette transparency flags (like a call to palt())
In the same spirit, the start of _draw() should reset both pal() and palt()
With those changes, the cart I tested worked perfectly.

**Comment by Shoozza** [comment]
Hi do you still have the cart you used for testing?

**Comment by TheNuSan** [comment]
Hi, it seems some of the issues have been fixed in the last version of PicoLove. I made a super simple cart to highlight two remaining issues I found : 
[testpal.zip](https://github.com/picolove/picolove/files/405789/testpal.zip)
The two issues remaining are : 
- pal() with no parameter should reset transparency flags (same as calling palt())
- cls() should take the clear color as a parameter
  It seems I have been mistaken and the start of _draw doesnt need to reset pal and palt, so no issue there.

**Comment by Shoozza** [comment]
I merged a pull request which should fix the pal issue

This seems to solve the cls issue, though im not sure how to get love.graphics.clear to work properly
```
function cls(c)
  c = c and flr(c) or 0
  love.graphics.setColor(c*16,0,0,255)
  love.graphics.rectangle('fill',0,0,128,128)
  love.graphics.setColor(__pico_color*16,0,0,255)
  __pico_cursor = {0,0}
end
```

I'll merge it if I find no better way.

**Comment by Shoozza** [comment]
Merged
