### ISSUE TITLE
Project dead?

### ISSUE THREAD

**Issue by Shoozza** [picolove/picolove#55]
Hi, are you still working on this?
There are still a few open pull request without any feedback.

Would be sad to see this die because of inactivity.

**Comment by gingerbeardman** [comment]
most development is now on this fork: https://github.com/gamax92/picolove

**Comment by Shoozza** [comment]
The project moved to the picolove organization on github and I have commit access now.

**Comment by josefnpat** [comment]
This is a good initiative!

1) Has changes from https://github.com/gamax92/picolove been merged upstream?
2) I think you should consider giving @gamax92 commit access too.

**Comment by gamax92** [comment]
I dunno ... my fork is based on an older version of picolove because I disliked the newer changes that happened, it wouldn't run properly on my phone and instead just lag terribly while still having several bugs and issues that haven't ever been fixed.

But I don't mind helping out if possible, even if it's just with PRs

**Comment by gingerbeardman** [comment]
@gamax92  what were the bad changes you refer to?

**Comment by gamax92** [comment]
There's a branch where all of the love2d graphics calls were being removed and replaced with software rendering in hopes to get the peek/poke/memset/memcpy stuff to work properly and that absolutely kills performance on my device and also seems largely unnecessary.

So in my own emulator I've been building from the ground up to be clean (not my picolove fork), one of the things it does is keeps using love2d graphics calls and will synchronize the two states (love2d graphics/memory) whenever it's needed, if a game never uses those 4 functions I mentioned then no synchronization occurs and it only will use love2d graphics calls, and even then that's only if it happens to be editing sprites, map, or screen directly. Also it has an optional software renderer that actually doesn't destroy performance on my device and runs great instead. A few of the stuff written for that has also been ported over to my picolove fork.

I need to get it up to date with 0.1.8's changes though, it took a small hiatus after motivation loss.

**Comment by gingerbeardman** [comment]
@gamax92 sounds great! i look forward to trying it out when it's ready.

I agree that the software rendering seems like overkill for this.

**Comment by Shoozza** [comment]
@josefnpat 
1) not yet.
I have to review @gamax92's pull request it contains several changes.
2) help is always welcome, I hope @ftsf also voices his opinion

I don't plan to continue the work on the software rendering branch.

It's great to see people care about this project! ;)
