### ISSUE TITLE
pget crash, (love 0.10.1 Incompatibility)

### ISSUE THREAD

**Issue by Rami-Sabbagh** [picolove/picolove#58]
I'm trying to run a game called light bikes http://www.lexaloffle.com/bbs/?tid=2501
that uses pget as a test collision mechanism, so I looked on the code of pget and I found it calling :getPixel(x,y) on the screen canvas, in love 10 this function has been removed, and now you have to do Canvas:newImageData( ), And that will drop fps a lot .

The solution is that you create 2 things: canvas, imagedata
then whenever something get drawn on the canvas you will have to do imagedata:setPixel

**Comment by Shoozza** [comment]
This fixes the issue but without optimizations.
It should work the same way as in the old LÖVE 0.9 implementation.
Optimizations might follow later.
