### ISSUE TITLE
PNG loading doesn't support v8 files

### ISSUE THREAD

**Issue by gingerbeardman** [picolove/picolove#59]
PNG loading doesn't support v8 files

And maybe other versions?

```
Matts-iMac:picolove matt$ love . 26413.p8.png 
Loading /26413.p8.png
version 8
codelen 27094
Error: main.lua:598: unknown file version 8
stack traceback:
    [C]: in function 'error'
    main.lua:598: in function 'load_p8'
    main.lua:1705: in function '_load'
    main.lua:352: in function 'load'
    main.lua:888: in function <main.lua:878>
    [C]: in function 'xpcall'
```

**Comment by gamax92** [comment]
it's likely that even though pico-8 is storing 8 in the version info, that it was just a number increase and nothing inside changed. All it'd take for picolove to do is bump up the number it supports

**Comment by gingerbeardman** [comment]
I'll try this out

**Comment by Shoozza** [comment]
Tested.  
Loading the file doesn't result in a version error message.  
Assuming the file was: https://www.lexaloffle.com/bbs/cposts/2/26413.p8.png
