### ISSUE TITLE
Missing player input keys

### ISSUE THREAD

**Issue by josefnpat** [picolove/picolove#6]
In the manual for 0.1.2, it says:

```
Player 1 keys: Cursors + ZX / NM
Player 2 keys: SDFE + tab,Q / shift A
```

from the keymap defined in main.lua:

```
__keymap = {
    [0] = {
        [0] = 'left',
        [1] = 'right',
        [2] = 'up',
        [3] = 'down',
        [4] = 'z',
        [5] = 'x',
    },
    [1] = {
        [0] = 's',
        [1] = 'f',
        [2] = 'e',
        [3] = 'd',
        [4] = 'q',
        [5] = 'a',
    }
}
```

it looks like the `nm`/`lshift/a` is missing.

This would be nice to add for familiarity with the picolove system!

**Comment by gingerbeardman** [comment]
@josefnpat you should make a pull request with the required changes, this is an easy one to get started with.

**Comment by josefnpat** [comment]
Cool, I didn't know if you wanted PR's, etc. I'll make one soon.

**Comment by gingerbeardman** [comment]
@josefnpat it's not my project, but I've had pull requests of mine merged into master

**Comment by ftsf** [comment]
thanks! PRs are always welcome here! =)

**Comment by josefnpat** [comment]
Well, check #10 !

**Comment by josefnpat** [comment]
bump - is this PR ok, or do I need to fix something?

**Comment by ftsf** [comment]
sorry, tested now, works well! merged.
