### ISSUE TITLE
List of working P8 Carts?

### ISSUE THREAD

**Issue by stefanhaustein** [picolove/picolove#66]
Hi, I am trying to get Pico Love running on Love Android....
Do you have a list of compatible carts for testing?
https://www.youtube.com/watch?v=zYKWbOpeaYM

**Comment by gamax92** [comment]
Bah, thanks for the crash report, I'll get that fixed up.

In the meantime though, you might be interested in trying out my https://github.com/gamax92/picolove/ fork, it's a bit better maintained, has some features useful for Android such as a touchscreen overlay for input, and I know Celeste runs fine on it (Celeste is one of my go to testing carts for doing Android testing)

**Comment by gamax92** [comment]
I believe this issue has been fixed, as Celeste seems to be running on picolove.
