### ISSUE TITLE
Something went wrong?

### ISSUE THREAD

**Issue by egordorichev** [picolove/picolove#69]
Hello! Just found your awesome project. Downloaded it, and compiled (I mean zipped it up). But here is a thing: I can't install demos. It says:

```
syntax error
'=' expected near '<EOF>'
```

Maybe i'm doing something wrong? Thanks!

**Comment by Shoozza** [comment]
Hello!
try following:
load yourdemoname
run

**Comment by egordorichev** [comment]
Sorry, what are the demos names?

**Comment by Shoozza** [comment]
There are no demos included at this point.
You can copy and edit the nocart.p8 file.
You can try your luck with some in the pico-8 site but they might not work.

**Comment by egordorichev** [comment]
Ok, thanks. So there is no way to create a new file inside pico-love?

**Comment by Shoozza** [comment]
Inside picolove? Sadly no.
You could create a p8 cart for editing p8 carts and then it would be possible ;)
