### ISSUE TITLE
Identify matching pico8 version

### ISSUE THREAD

**Issue by josefnpat** [picolove/picolove#7]
It would be nice to identify what version of pico8 that picolove will run. It looks like it's currently `0.1.1`*

The current version is 0.1.2.

What would be nice is if there was a way to read the version from the file header, so that appropriate regressions could take place.

*_From the readme, it mentions that `sqrt` crashes pico8. From this [list of known bugs](http://pico-8.wikia.com/wiki/Known_Bugs) it looks like the sqrt bug was in 0.1.1._

**Comment by ftsf** [comment]
I'm not sure about this, picolove is likely never going to be 100% compatible with a specific pico8 version, but will always try to catch up with the latest version, so I don't know that claiming compatibility with a specific version is a good idea.
