### ISSUE TITLE
Some colors are not displayed

### ISSUE THREAD

**Issue by egordorichev** [picolove/picolove#71]
Hello!
Was playing around your awesome project!
One thing I found, that it doesn't display colors 15 and 14:

![](http://i.imgur.com/ZCX047w.png)

I **did not** modify the source code or something else.
Thanks, Egor.

**Comment by gamax92** [comment]
Color 14 is there, the pink on the left of the heart.
Color 15 is likely gone due to a shader upload bug in Love2D 0.10.2

I'll add a workaround to this project soon.

**Comment by gamax92** [comment]
Fixed by e33f750f22915e3d115152c0326cabe1f68b14d7
