### ISSUE TITLE
Not compatible with LOVE 11.5 (latest)

### ISSUE THREAD

**Issue by gingerbeardman** [picolove/picolove#74]
on launch:
<img width="420" alt="screen shot 2019-02-22 at 12 29 21" src="https://user-images.githubusercontent.com/49612/53242731-83c4f800-369d-11e9-8b77-7ac675899853.png">

on run:
<img width="580" alt="screen shot 2019-02-22 at 12 29 24" src="https://user-images.githubusercontent.com/49612/53242739-8aec0600-369d-11e9-88ef-8c69a63b5b5e.png">

**Comment by Shoozza** [comment]
Will happen as part of the merge #70

**Comment by gingerbeardman** [comment]
(removed)

**Comment by gamax92** [comment]
@gingerbeardman
I'm unable to reproduce that error with my fork, and I don't see why that could possibly be an issue. It's part of the default love.run in LÖVE's [boot.lua](https://bitbucket.org/rude/love/src/825682216bf4d94220dbd9c25d0c394178627aa0/src/scripts/boot.lua?at=default&fileviewer=file-view-default#boot.lua-577)

**Comment by gingerbeardman** [comment]
@gamax92 indeed, no idea what I was doing - sorry for the false alarm!

**Comment by Shoozza** [comment]
Since my other PC has an issue with text rendering, migration will happen once 11.3 is out https://love2d.org/wiki/11.3

**Comment by tobiasvl** [comment]
11.3 is now out

**Comment by Shoozza** [comment]
Oh seems like I missed your message.
Yeah ideally Love2d ~~11.3~~ 11.4 can become the default version as soon as it works properly.

Btw running with different versions is possible now with:
`make 9` for Löve 0.9.x
`make 10` for Löve 0.10.x
`make 11` for Löve 11.x

**Comment by Anikmoujegy** [comment]
not supported in love 11.4

**Comment by Shoozza** [comment]
Compatibility warning removed for 11.5 (other 11.x versions will get the warning).
Left some filesystem warnings for later.
