### ISSUE TITLE
What is picolove licensed under?

### ISSUE THREAD

**Issue by josefnpat** [picolove/picolove#8]
If you have not chosen one, I would suggest the liberal [zlib/libpng license](https://opensource.org/licenses/Zlib) as that is what love and many love libraries use.

There is [the license that the site uses](http://www.lexaloffle.com/info.php?page=tos) but that's more of a TOS for the site.

They do seem to [push cc4-attr-nc-sa quite a bit as well.](http://www.lexaloffle.com/bbs/?tid=2184) but I would still advise against it, looking at how the love community uses libraries.

**Comment by josefnpat** [comment]
bump - I'd like to know before I offer more PR's :cry:

**Comment by ftsf** [comment]
Good question, something very liberal, let's go with Zlib License =)

**Comment by ftsf** [comment]
fixed in bf2bbb36191ad61ef0e430db40e2772db13ea143
