### ISSUE TITLE
unknown file version 5

### ISSUE THREAD

**Issue by josefnpat** [picolove/picolove#9]
I get this error when loading `.v8.png` files, which makes sense considering I'm guessing picolove is for `0.1.1` and not `0.1.2`.

![http://i.imgur.com/bthFCkK.png](http://i.imgur.com/bthFCkK.png)

I mention this because it is inconsistent with the `.v8` files.

Might make more sense to show a warning instead for both filetypes, and then attempt to run it anyway?

**Comment by ftsf** [comment]
version 5 is now handled.

**Comment by josefnpat** [comment]
:+1:
