### ISSUE TITLE
Doesn't work with love 11.5.1

### ISSUE THREAD

**Issue by Anikmoujegy** [picolove/picolove#96]
![image](https://github.com/picolove/picolove/assets/119772397/e0ff167d-d1a0-4b3b-a1d3-d9ba68e88353)

At first, a pop-up appeared on when I tried to run picolove.
Then colors are abnormal like above, then when I try to type help or load a game the screen becomes black.
What should I do ?

**Comment by Shoozza** [comment]
Should be fixed in the latest version :)

**Comment by Anikmoujegy** [comment]
thanks
